### ISSUE TITLE
Consider adding a new maintainer

### ISSUE THREAD

**Issue by caniszczyk** [opencontainers/runtime-tools#237]
Ma Shimiao (mashimiao.fnst@cn.fujitsu.com) has done quite a bit of work so far!

https://github.com/opencontainers/runtime-tools/commits?author=Mashimiao

cc: @mrunalp

**Comment by mrunalp** [comment]
:+1: We can update the existing maintainer list and then open another PR as @wking suggested.

**Comment by stephenrwalli** [comment]
So as Chris isn't himself a maintainer, should an existing maintainer set up the PR to add Ma Shimiao per the rules [1] to start the 5-day voting period?  

[1] https://github.com/opencontainers/project-template/blob/52dbb39db883d7eeacf62865b028c4154578e5c3/MAINTAINERS_GUIDE.md#how-are-maintainers-added

**Comment by wking** [comment]
On Tue, Oct 11, 2016 at 01:14:58PM -0700, Stephen Walli wrote:
> So as Chris isn't himself a maintainer, should an existing
> maintainer set up the PR to add Ma Shimiao per the rules [1] to
> start the 5-day voting period?
> 
> [1] https://github.com/opencontainers/project-template/blob/52dbb39db883d7eeacf62865b028c4154578e5c3/MAINTAINERS_GUIDE.md#how-are-maintainers-added 

I don't actually see anything in there about needing an existing
maintainer to sponsor, unless it is covered by [1] (in which case the
wording should be made more explicit, because the MAINTAINERS_GUIDE
wording predates GOVERNANCE).  I'd submit a project-template PR to
make the “anyone can (or can't?) sponsor a new maintainer” bit
explicit, but there's currently a backlog of project-template PRs [2].

Looking at previous examples, @cyphar nominated himself in
opencontainers/runC#503.  So I expect it's fine for anyone to file the
PR until we have clearer wording in the MAINTAINERS_GUIDE.

[1]: https://github.com/opencontainers/project-template/blob/52dbb39db883d7eeacf62865b028c4154578e5c3/GOVERNANCE.md#proposing-a-motion
[2]: https://github.com/opencontainers/project-template/pulls

**Comment by wking** [comment]
On Tue, Oct 11, 2016 at 01:23:48PM -0700, W. Trevor King wrote:
> I'd submit a project-template PR to make the “anyone can (or can't?)
> sponsor a new maintainer” bit explicit, but there's currently a
> backlog of project-template PRs [2].

Actually, it looks like I've already submitted a project-template PR
that (among other things) explicitly ties maintainer addition to
GOVERNANCE [1].

[1]: https://github.com/opencontainers/project-template/pull/20/commits/0787a4187c32d32fb0e9af84306a9512c74e81ec#diff-cc177b5b54bfdc5f9e1697d2c1ec1dc0R87

**Comment by initlove** [comment]
+1 for 'Adding Ma Shimiao'.

Also @wking has done lots lots of work so far.
Hi @wking, would like to be a maintainer?

I suggest to add both of them.  @mrunalp @caniszczyk

**Comment by liangchenye** [comment]
+1 for 'Adding Ma Shimiao'.

Also @wking has done lots lots of work so far.
Hi @wking, would like to be a maintainer?

I suggest to add both of them. @mrunalp @caniszczyk

**Comment by wking** [comment]
On Tue, Oct 11, 2016 at 07:36:26PM -0700, 梁辰晔 (Liang Chenye) wrote:
> Also @wking has done lots lots of work so far.
> Hi @wking, would like to be a maintainer?

9 maintainers inherited from runtime-spec plus @Mashimiao and
@liangchenye is probably enough hands at the wheel ;).  Especially
since I'd prefer fairly different tracks than the current approaches
for both config and runtime validation [1,2].  I'm happy to keep
contibuting as a non-maintainer to avoid bogging down
consensus-forming with my opinions.

[1]: https://github.com/opencontainers/runtime-tools/issues/66#issuecomment-235753741
[2]: https://github.com/opencontainers/runtime-tools/issues/98

**Comment by mrunalp** [comment]
@caniszczyk Could you setup @liangchenye and @Mashimiao with maintainer privileges on this repo now that they have been added to the MAINTAINER list?

**Comment by caniszczyk** [comment]
@mrunalp done, I added them to @opencontainers/runtime-tools-maintainers pending they accept the invite

**Comment by mrunalp** [comment]
Thanks!
