### ISSUE TITLE
environment generation causes duplicate entries

### ISSUE THREAD

**Issue by cyphar** [opencontainers/runtime-tools#290]
If you set an environment variable to a different value, you will get two entries in `process.env`. Apart from being an eyesore, POSIX doesn't actually specify what should happen if you have two variables set with the same name.

```
% oci-runtime-tool generate --env A=B --env A=C
...
                "env": [
                        "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                        "TERM=xterm",
                        "A=B",
                        "A=C"
                ],
...
```

IMO we should change the environment setting signature to something like `AddProcessEnv(key, value string)`. Or we add parsing to the code so we replace entries if we see them.

**Comment by wking** [comment]
On Wed, Dec 14, 2016 at 06:31:34AM -0800, Aleksa Sarai wrote:
> IMO we should change the environment setting signature to something
> like `AddProcessEnv(key, value string)`. Or we add parsing to the
> code so we replace entries if we see them.

Having the signature take explicit key/value args sounds good to me,
because it will make an eventual RemoveProcessEnv(key string) more
consistent.

There's an outside chance that someone would want a no-clobber version
of AddProcessEnv, but until we actually hear someone ask for it I
think we can go ahead with a signature/implementation that always
clobbers when a key already exists in the environment variable array.
