### ISSUE TITLE
Way to tell error messages with different compliance levels.

### ISSUE THREAD

**Issue by liangchenye** [opencontainers/runtime-tools#362]
Discussed in https://github.com/opencontainers/runtime-tools/pull/354. @wking recommends we can using [TAG native diagnostics](https://testanything.org/tap-version-13-specification.html#diagnostics) to tell the different compliance levels of validating messages.

**Comment by liangchenye** [comment]
checked in. close.

**Comment by wking** [comment]
On Tue, Aug 29, 2017 at 08:14:03PM -0700, 梁辰晔 (Liang Chenye) wrote:
> checked in. close.

I don't think we can close this yet, because master gives me no
guidance about MUST/SHOULD/etc. in the output:

  $ oci-runtime-tool --version
  oci-runtime-tool version 0.0.1, commit: 12b47b989d39e3e750fff2631e929f455b6eef3f
  $ oci-runtime-tool validate
  3 errors occurred:

  * 'POSIXRlimit.Type' should not be empty
  * validate currently only handles version 1.0.0, but the supplied configuration targets 1.0.0-rc6
  * rlimit type "" is invalid

and, unlike runtimetest since #354, ‘oci-runtime-tool validate’ does
not support the --compliance-level option.

**Comment by wking** [comment]
Also, this issue may be a dup of #335.  I think one or the other should be re-opened, at least until `validate` gets `--compliance-level`.

**Comment by wking** [comment]
> … at least until `validate` gets `--compliance-level`.

This is in-flight now with #492.

And I'm still in favor of [TAP diagnostics][1] as a human- and machine-readable way to report these.  #439 is an in-flight implementation of that for `runtimetest`, and if/when it lands I can work up something similar for `oci-runtime-tool validate`.

[1]: https://testanything.org/tap-version-13-specification.html#diagnostics
